import { Category, Product, Company, Configs, BorderOption, AdditionalOption } from "../types";

export const DEFAULT_BORDERS: BorderOption[] = [
  { name: "Massa simples", price: 0 },
  { name: "Catupiry", price: 5.0 },
  { name: "Cheddar", price: 7.0 },
  { name: "Chocolate", price: 10.0 },
];

export const DEFAULT_ADDITIONALS: AdditionalOption[] = [
  { name: "Bacon Extra", price: 5.0 },
  { name: "Mussarela Extra", price: 4.5 },
  { name: "Calabresa Extra", price: 4.5 },
  { name: "Catupiry Extra", price: 4.0 },
  { name: "Cheddar Extra", price: 4.5 },
  { name: "Cebola Extra", price: 2.0 },
  { name: "Azeitona Extra", price: 2.0 },
];

export const DEFAULT_COMPANY: Company = {
  name: "Rei da Pizza - Forno a Lenha",
  logo: "", // Empty by default as requested: "Quando a logo não tiver imagem, mostrar o nome da empresa em texto."
  banner_title: "Verdadeira Pizza Feita no Forno a Lenha",
  banner_subtitle: "Forno a Lenha • Pizza Inteira 8 Pedaços • Meio a Meio Disponível",
};

export const DEFAULT_CONFIGS: Configs = {
  whatsapp: "+55 800 000 3728",
  delivery_fee: 7.0,
  working_hours_start: "18:00",
  working_hours_end: "23:30",
  closed_message: "Estamos fechados no momento. Você ainda pode visualizar o cardápio.",
  is_force_closed: false,
};

export const DEFAULT_CATEGORIES: Category[] = [
  { id: "cat-salgada", name: "Pizzas Salgadas", active: true, order: 1 },
  { id: "cat-doce", name: "Pizzas Doces", active: true, order: 2 },
  { id: "cat-esfirra-salgada", name: "Esfirras Salgadas", active: true, order: 3 },
  { id: "cat-esfirra", name: "Esfirras Doces", active: true, order: 4 },
  { id: "cat-bebida", name: "Bebidas", active: true, order: 5 },
];

export const DEFAULT_PRODUCTS: Product[] = [
  // CATEGORIA: PIZZAS SALGADAS (cat-salgada)
  {
    id: "prod-sal-mussarela",
    name: "Mussarela",
    photo: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600&auto=format&fit=crop&q=80",
    description: "Clássica mussarela com molho de tomate fresco e azeitonas.",
    ingredients: "Molho de tomate artesanal, bastante mussarela ralada, rodelas de tomate fresco, azeitonas e orégano.",
    price: 34.90,
    category_id: "cat-salgada",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Catupiry", "Cheddar", "Chocolate"],
    additionals_available: ["Bacon Extra", "Mussarela Extra", "Calabresa Extra", "Catupiry Extra", "Cheddar Extra", "Cebola Extra", "Azeitona Extra"],
  },
  {
    id: "prod-sal-calabresa",
    name: "Calabresa",
    photo: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80",
    description: "Calabresa fatiada selecionada, cebola branca fresca e farta mussarela.",
    ingredients: "Molho de tomate caseiro, mussarela, calabresa defumada fatiada e cebola caramelizada.",
    price: 34.90,
    category_id: "cat-salgada",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Catupiry", "Cheddar", "Chocolate"],
    additionals_available: ["Bacon Extra", "Mussarela Extra", "Calabresa Extra", "Catupiry Extra", "Cheddar Extra", "Cebola Extra", "Azeitona Extra"],
  },
  {
    id: "prod-sal-portuguesa",
    name: "Portuguesa",
    photo: "https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=600&auto=format&fit=crop&q=80",
    description: "Completa, tradicional com presunto, ovos, milho, ervilhas e cebola.",
    ingredients: "Mussarela premium, presunto cozido, fatias de ovos, milho, ervilha, cebola e azeitonas pretas.",
    price: 39.90,
    category_id: "cat-salgada",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Catupiry", "Cheddar", "Chocolate"],
    additionals_available: ["Bacon Extra", "Mussarela Extra", "Calabresa Extra", "Catupiry Extra", "Cheddar Extra", "Cebola Extra", "Azeitona Extra"],
  },
  {
    id: "prod-sal-frango-catupiry",
    name: "Frango com Catupiry",
    photo: "https://images.unsplash.com/photo-1544982503-9f984c14501a?w=600&auto=format&fit=crop&q=80",
    description: "Peito de frango desfiado temperado coberto com legítimo requeijão Catupiry.",
    ingredients: "Molho de tomate da casa, peito de frango selecionado desfiado e temperado, Catupiry cremoso e orégano.",
    price: 39.90,
    category_id: "cat-salgada",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Catupiry", "Cheddar", "Chocolate"],
    additionals_available: ["Bacon Extra", "Mussarela Extra", "Calabresa Extra", "Catupiry Extra", "Cheddar Extra", "Cebola Extra", "Azeitona Extra"],
  },
  {
    id: "prod-sal-marguerita",
    name: "Marguerita",
    photo: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600&auto=format&fit=crop&q=80",
    description: "Clássica marguerita perfumada com folhas de manjericão gigante.",
    ingredients: "Molho de tomate artesanal, mussarela, rodelas de tomate fresco, manjericão fresco, azeite extra virgem e parmesão salpicado.",
    price: 39.90,
    category_id: "cat-salgada",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Catupiry", "Cheddar", "Chocolate"],
    additionals_available: ["Bacon Extra", "Mussarela Extra", "Calabresa Extra", "Catupiry Extra", "Cheddar Extra", "Cebola Extra", "Azeitona Extra"],
  },
  {
    id: "prod-sal-quatro-queijos",
    name: "Quatro Queijos",
    photo: "https://images.unsplash.com/photo-1590947132387-155cc02f3212?w=600&auto=format&fit=crop&q=80",
    description: "Combinação irresistível de queijos nobres selecionados derretidos.",
    ingredients: "Mussarela de base, provolone fatiado defumado, gorgonzola nobre e requeijão premium.",
    price: 44.90,
    category_id: "cat-salgada",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Catupiry", "Cheddar", "Chocolate"],
    additionals_available: ["Bacon Extra", "Mussarela Extra", "Calabresa Extra", "Catupiry Extra", "Cheddar Extra", "Cebola Extra", "Azeitona Extra"],
  },
  {
    id: "prod-sal-bacon",
    name: "Bacon",
    photo: "https://images.unsplash.com/photo-1613564834361-9436948817d1?w=600&auto=format&fit=crop&q=80",
    description: "Mussarela sob generosos cubinhos de bacon premium crocantes.",
    ingredients: "Molho de tomate, mussarela premium farta e bastante bacon tostado bem crocante.",
    price: 44.90,
    category_id: "cat-salgada",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Catupiry", "Cheddar", "Chocolate"],
    additionals_available: ["Bacon Extra", "Mussarela Extra", "Calabresa Extra", "Catupiry Extra", "Cheddar Extra", "Cebola Extra", "Azeitona Extra"],
  },
  {
    id: "prod-sal-milho-bacon",
    name: "Milho com Bacon",
    photo: "https://images.unsplash.com/photo-1594007654729-407ededc4963?w=600&auto=format&fit=crop&q=80",
    description: "Milho verde selecionado doce com cubos salgados de bacon.",
    ingredients: "Molho de tomate, mussarela premium, milho verde tenro e cubos dourados de bacon fritos.",
    price: 44.90,
    category_id: "cat-salgada",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Catupiry", "Cheddar", "Chocolate"],
    additionals_available: ["Bacon Extra", "Mussarela Extra", "Calabresa Extra", "Catupiry Extra", "Cheddar Extra", "Cebola Extra", "Azeitona Extra"],
  },
  {
    id: "prod-sal-atum",
    name: "Atum",
    photo: "https://images.unsplash.com/photo-1555072956-7758afb20e8f?w=600&auto=format&fit=crop&q=80",
    description: "Fatias de atum sólido com cebola roxa marinada em azeite.",
    ingredients: "Molho de tomate, mussarela, atum sólido selecionado ralado, cebola branca fatiada fina e orégano.",
    price: 44.90,
    category_id: "cat-salgada",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Catupiry", "Cheddar", "Chocolate"],
    additionals_available: ["Bacon Extra", "Mussarela Extra", "Calabresa Extra", "Catupiry Extra", "Cheddar Extra", "Cebola Extra", "Azeitona Extra"],
  },
  {
    id: "prod-sal-carne-seca",
    name: "Carne Seca com Catupiry",
    photo: "https://images.unsplash.com/photo-1590947132387-155cc02f3212?w=600&auto=format&fit=crop&q=80",
    description: "Carne seca temperada desfiada com farto Catupiry legítimo.",
    ingredients: "Mussarela farta, carne seca desfiada de primeira temperada e cebola roxa com Catupiry original salpicado.",
    price: 49.90,
    category_id: "cat-salgada",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Catupiry", "Cheddar", "Chocolate"],
    additionals_available: ["Bacon Extra", "Mussarela Extra", "Calabresa Extra", "Catupiry Extra", "Cheddar Extra", "Cebola Extra", "Azeitona Extra"],
  },
  {
    id: "prod-sal-napolitana",
    name: "Napolitana",
    photo: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600&auto=format&fit=crop&q=80",
    description: "Tradicional receita com parmesão ralado e tomates frescos.",
    ingredients: "Molho de tomate, mussarela premium, parmesão salpicado, rodelas de tomate fresco marinado e orégano.",
    price: 39.90,
    category_id: "cat-salgada",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Catupiry", "Cheddar", "Chocolate"],
    additionals_available: ["Bacon Extra", "Mussarela Extra", "Calabresa Extra", "Catupiry Extra", "Cheddar Extra", "Cebola Extra", "Azeitona Extra"],
  },
  {
    id: "prod-sal-toscana",
    name: "Toscana",
    photo: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80",
    description: "Deliciosa combinação de calabresa moída com queijo.",
    ingredients: "Molho de tomate caseiro, mussarela farta, calabresa moída especial pré-assada e orégano.",
    price: 39.90,
    category_id: "cat-salgada",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Catupiry", "Cheddar", "Chocolate"],
    additionals_available: ["Bacon Extra", "Mussarela Extra", "Calabresa Extra", "Catupiry Extra", "Cheddar Extra", "Cebola Extra", "Azeitona Extra"],
  },
  {
    id: "prod-sal-baiana",
    name: "Baiana",
    photo: "https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=600&auto=format&fit=crop&q=80",
    description: "Picância na medida ideal com calabresa moída e pimenta.",
    ingredients: "Mussarela premium, calabresa moída especial de primeira, fatias de ovos, cebola roxa e pimenta calabresa em flocos.",
    price: 39.90,
    category_id: "cat-salgada",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Catupiry", "Cheddar", "Chocolate"],
    additionals_available: ["Bacon Extra", "Mussarela Extra", "Calabresa Extra", "Catupiry Extra", "Cheddar Extra", "Cebola Extra", "Azeitona Extra"],
  },
  {
    id: "prod-sal-moda-casa",
    name: "Moda da Casa",
    photo: "https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=600&auto=format&fit=crop&q=80",
    description: "A receita secreta especial com diversidade de recheio.",
    ingredients: "Molho, mussarela, presunto picado, bacon em cubos, Catupiry legítimo, milho e orégano.",
    price: 49.90,
    category_id: "cat-salgada",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Catupiry", "Cheddar", "Chocolate"],
    additionals_available: ["Bacon Extra", "Mussarela Extra", "Calabresa Extra", "Catupiry Extra", "Cheddar Extra", "Cebola Extra", "Azeitona Extra"],
  },
  {
    id: "prod-sal-pepperoni",
    name: "Pepperoni",
    photo: "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=600&auto=format&fit=crop&q=80",
    description: "Rodelas crocantes de salame Pepperoni de primeira qualidade.",
    ingredients: "Molho de tomate artesanal, muita mussarela ralada, fatias generosas de pepperoni e orégano.",
    price: 49.90,
    category_id: "cat-salgada",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Catupiry", "Cheddar", "Chocolate"],
    additionals_available: ["Bacon Extra", "Mussarela Extra", "Calabresa Extra", "Catupiry Extra", "Cheddar Extra", "Cebola Extra", "Azeitona Extra"],
  },
  {
    id: "prod-sal-lombo-catupiry",
    name: "Lombo com Catupiry",
    photo: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80",
    description: "Lombo canadense fatiado delicioso com legítimo Catupiry.",
    ingredients: "Molho da casa, lombo tipo canadense desfiado e fatiado, cebola branca fina, Catupiry original.",
    price: 49.90,
    category_id: "cat-salgada",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Catupiry", "Cheddar", "Chocolate"],
    additionals_available: ["Bacon Extra", "Mussarela Extra", "Calabresa Extra", "Catupiry Extra", "Cheddar Extra", "Cebola Extra", "Azeitona Extra"],
  },
  {
    id: "prod-sal-calabresa-especial",
    name: "Calabresa Especial",
    photo: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80",
    description: "Uma versão nobre de calabresa fatiada com bacon e Catupiry.",
    ingredients: "Molho, mussarela, calabresa fatiada, bacon crocante, Catupiry e cebola roxa picada.",
    price: 44.90,
    category_id: "cat-salgada",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Catupiry", "Cheddar", "Chocolate"],
    additionals_available: ["Bacon Extra", "Mussarela Extra", "Calabresa Extra", "Catupiry Extra", "Cheddar Extra", "Cebola Extra", "Azeitona Extra"],
  },
  {
    id: "prod-sal-americana",
    name: "Americana",
    photo: "https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=600&auto=format&fit=crop&q=80",
    description: "Deliciosa mistura com presunto, palmito, bacon e ovos.",
    ingredients: "Mussarela, presunto picado, palmito em fatias, bacon tostado, ovos fatiados e orégano.",
    price: 44.90,
    category_id: "cat-salgada",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Catupiry", "Cheddar", "Chocolate"],
    additionals_available: ["Bacon Extra", "Mussarela Extra", "Calabresa Extra", "Catupiry Extra", "Cheddar Extra", "Cebola Extra", "Azeitona Extra"],
  },
  {
    id: "prod-sal-caipira",
    name: "Caipira",
    photo: "https://images.unsplash.com/photo-1544982503-9f984c14501a?w=600&auto=format&fit=crop&q=80",
    description: "Frango desfiado temperado com muito milho e requeijão.",
    ingredients: "Molho de tomate, frango temperado desfiado, milho tenro selecionado, Catupiry legítimo.",
    price: 44.90,
    category_id: "cat-salgada",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Catupiry", "Cheddar", "Chocolate"],
    additionals_available: ["Bacon Extra", "Mussarela Extra", "Calabresa Extra", "Catupiry Extra", "Cheddar Extra", "Cebola Extra", "Azeitona Extra"],
  },
  {
    id: "prod-sal-brocolis-bacon",
    name: "Brócolis com Bacon",
    photo: "https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=600&auto=format&fit=crop&q=80",
    description: "Brócolis frescos cozidos no vapor cobertos por bacon defumado crocante.",
    ingredients: "Mussarela premium, brócolis ninja temperados, alho frito salpicado e cubinhos de bacon frito.",
    price: 49.90,
    category_id: "cat-salgada",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Catupiry", "Cheddar", "Chocolate"],
    additionals_available: ["Bacon Extra", "Mussarela Extra", "Calabresa Extra", "Catupiry Extra", "Cheddar Extra", "Cebola Extra", "Azeitona Extra"],
  },
  {
    id: "prod-sal-brocolis-catupiry",
    name: "Brócolis com Catupiry",
    photo: "https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=600&auto=format&fit=crop&q=80",
    description: "Deliciosos brócolis ninja com o requinte do legítimo Catupiry.",
    ingredients: "Brócolis selecionados picadinhos, bastante mussarela ralada, Catupiry original em fios generosos.",
    price: 49.90,
    category_id: "cat-salgada",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Catupiry", "Cheddar", "Chocolate"],
    additionals_available: ["Bacon Extra", "Mussarela Extra", "Calabresa Extra", "Catupiry Extra", "Cheddar Extra", "Cebola Extra", "Azeitona Extra"],
  },
  {
    id: "prod-sal-palmito",
    name: "Palmito",
    photo: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80",
    description: "Generoso recheio de palmitos brancos e macios selecionados.",
    ingredients: "Molho artesanal, mussarela de qualidade, palmito fatiado nobre e orégano.",
    price: 44.90,
    category_id: "cat-salgada",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Catupiry", "Cheddar", "Chocolate"],
    additionals_available: ["Bacon Extra", "Mussarela Extra", "Calabresa Extra", "Catupiry Extra", "Cheddar Extra", "Cebola Extra", "Azeitona Extra"],
  },
  {
    id: "prod-sal-palmito-bacon",
    name: "Palmito com Bacon",
    photo: "https://images.unsplash.com/photo-1613564834361-9436948817d1?w=600&auto=format&fit=crop&q=80",
    description: "Palmito nobre macio e doçura leve com salgadinho de bacon em cubos.",
    ingredients: "Molho, mussarela, generosos pedaços de palmito, bacon picado torradinho e orégano.",
    price: 49.90,
    category_id: "cat-salgada",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Catupiry", "Cheddar", "Chocolate"],
    additionals_available: ["Bacon Extra", "Mussarela Extra", "Calabresa Extra", "Catupiry Extra", "Cheddar Extra", "Cebola Extra", "Azeitona Extra"],
  },
  {
    id: "prod-sal-alho-oleo",
    name: "Alho e Óleo",
    photo: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600&auto=format&fit=crop&q=80",
    description: "Simplicidade perfumada com alho crocante frito no azeite.",
    ingredients: "Molho de tomate fresco, mussarela, dentes de alho picados torrados crocantes e azeite de oliva extra virgem.",
    price: 39.90,
    category_id: "cat-salgada",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Catupiry", "Cheddar", "Chocolate"],
    additionals_available: ["Bacon Extra", "Mussarela Extra", "Calabresa Extra", "Catupiry Extra", "Cheddar Extra", "Cebola Extra", "Azeitona Extra"],
  },
  {
    id: "prod-sal-alho-poro-bacon",
    name: "Alho Poró com Bacon",
    photo: "https://images.unsplash.com/photo-1594007654729-407ededc4963?w=600&auto=format&fit=crop&q=80",
    description: "Alho poró refogado nobre, coberto com muito de bacon frito.",
    ingredients: "Mussarela de base, lâminas de alho poró refogadas, bacon em cubos estaladiço.",
    price: 49.90,
    category_id: "cat-salgada",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Catupiry", "Cheddar", "Chocolate"],
    additionals_available: ["Bacon Extra", "Mussarela Extra", "Calabresa Extra", "Catupiry Extra", "Cheddar Extra", "Cebola Extra", "Azeitona Extra"],
  },
  {
    id: "prod-sal-estrogonofe-frango",
    name: "Estrogonofe de Frango",
    photo: "https://images.unsplash.com/photo-1544982503-9f984c14501a?w=600&auto=format&fit=crop&q=80",
    description: "Autêntico estrogonofe de peito de frango com batata palha por cima.",
    ingredients: "Base de mussarela, cubos de frango em creme suave especial com champignon, salpicado com batata palha crocante.",
    price: 49.90,
    category_id: "cat-salgada",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Catupiry", "Cheddar", "Chocolate"],
    additionals_available: [],
  },
  {
    id: "prod-sal-estrogonofe-carne",
    name: "Estrogonofe de Carne",
    photo: "https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=600&auto=format&fit=crop&q=80",
    description: "Uma verdadeira explosão de sabor com carne em creme e batata palha.",
    ingredients: "Filé de carne picadinho refogado com creme de leite, base de mussarela premium e muita batata palha fresca por cima.",
    price: 54.90,
    category_id: "cat-salgada",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Catupiry", "Cheddar", "Chocolate"],
    additionals_available: [],
  },
  {
    id: "prod-sal-mexicana",
    name: "Mexicana",
    photo: "https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=600&auto=format&fit=crop&q=80",
    description: "Arretada com calabresa moída, pimenta vermelha, cebola e pimentões.",
    ingredients: "Mussarela, calabresa moída, cebola caramelizada fatiada, tiras de pimentão fresquinho e pimenta picante selecionada.",
    price: 49.90,
    category_id: "cat-salgada",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Catupiry", "Cheddar", "Chocolate"],
    additionals_available: ["Bacon Extra", "Mussarela Extra", "Calabresa Extra", "Catupiry Extra", "Cheddar Extra", "Cebola Extra", "Azeitona Extra"],
  },
  {
    id: "prod-sal-paulista",
    name: "Paulista",
    photo: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80",
    description: "Uma pizza bem recheada com milho, presunto, ervilha e palmito.",
    ingredients: "Base de de mussarela, presunto premium cozido picado, milho verde selecionado, ervilha fresca e rodelas de palmito macio.",
    price: 49.90,
    category_id: "cat-salgada",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Catupiry", "Cheddar", "Chocolate"],
    additionals_available: ["Bacon Extra", "Mussarela Extra", "Calabresa Extra", "Catupiry Extra", "Cheddar Extra", "Cebola Extra", "Azeitona Extra"],
  },
  {
    id: "prod-sal-tropical",
    name: "Tropical",
    photo: "https://images.unsplash.com/photo-1594007654729-407ededc4963?w=600&auto=format&fit=crop&q=80",
    description: "Refrescante harmonia doce-salgado de abacaxi com presunto.",
    ingredients: "Molho de tomate integral, queijo mussarela farto, pedaços de abacaxi fresco em calda nobre e tiras finas de presunto.",
    price: 44.90,
    category_id: "cat-salgada",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Catupiry", "Cheddar", "Chocolate"],
    additionals_available: ["Bacon Extra", "Mussarela Extra", "Calabresa Extra", "Catupiry Extra", "Cheddar Extra", "Cebola Extra", "Azeitona Extra"],
  },

  // CATEGORIA: PIZZAS DOCES (cat-doce)
  {
    id: "prod-doc-chocolate-leite",
    name: "Chocolate ao Leite",
    photo: "https://images.unsplash.com/photo-1619535860434-ba1d8fa12536?w=600&auto=format&fit=crop&q=80",
    description: "Generoso chocolate ao leite nobre cremoso salpicado com raspas.",
    ingredients: "Massa leve crocante pré-assada, cobertura espessa de chocolate ao leite culinário nobre e raspas decorativas.",
    price: 34.90,
    category_id: "cat-doce",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Chocolate"],
    additionals_available: [],
  },
  {
    id: "prod-doc-chocolate-branco",
    name: "Chocolate Branco",
    photo: "https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?w=600&auto=format&fit=crop&q=80",
    description: "Deliciosa e cremosa receita com cobertura de puro chocolate branco.",
    ingredients: "Massa leve de wrap ou pizza, chocolate branco derretido premium tipo ganache e raspas de chocolate nobre.",
    price: 39.90,
    category_id: "cat-doce",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Chocolate"],
    additionals_available: [],
  },
  {
    id: "prod-doc-prestigio",
    name: "Prestígio",
    photo: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&auto=format&fit=crop&q=80",
    description: "A consagrada união de chocolate cremoso com coco ralado úmido.",
    ingredients: "Base de chocolate ao leite derretido nobre salpicada com flocos de coco fesco cozido.",
    price: 39.90,
    category_id: "cat-doce",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Chocolate"],
    additionals_available: [],
  },
  {
    id: "prod-doc-brigadeiro",
    name: "Brigadeiro",
    photo: "https://images.unsplash.com/photo-1541783245831-57d6fb0926d3?w=600&auto=format&fit=crop&q=80",
    description: "Chocolate de brigadeiro de panela gourmet artesanal com granulados.",
    ingredients: "Especial brigadeiro cremoso cozido coberto por flocos de brigadeiro gourmet nobre e granulados e chocolate.",
    price: 39.90,
    category_id: "cat-doce",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Chocolate"],
    additionals_available: [],
  },
  {
    id: "prod-doc-sensacao",
    name: "Sensação",
    photo: "https://images.unsplash.com/photo-1619535860434-ba1d8fa12536?w=600&auto=format&fit=crop&q=80",
    description: "União fantástica de chocolate ao leite nobre com morangos frescos.",
    ingredients: "Pasta de chocolate ao leite culinário com morangos frescos picados dispostos com elegância.",
    price: 44.90,
    category_id: "cat-doce",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Chocolate"],
    additionals_available: [],
  },
  {
    id: "prod-doc-banana-canela",
    name: "Banana com Canela",
    photo: "https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?w=600&auto=format&fit=crop&q=80",
    description: "Aromáticas bananas fatiadas sobre fina mussarela com açúcar e canela.",
    ingredients: "Banana cortada fatiada de primeira em calda, açúcar cristal, canela premium polvilhada por cima.",
    price: 34.90,
    category_id: "cat-doce",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Chocolate"],
    additionals_available: [],
  },
  {
    id: "prod-doc-banana-chocolate",
    name: "Banana com Chocolate",
    photo: "https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?w=600&auto=format&fit=crop&q=80",
    description: "Bananas maduras selecionadas cobertas com calda nobre de chocolate.",
    ingredients: "Chocolate ao leite, rodelas grossas de banana fresca cozidas no forno, canela salpicada opcional.",
    price: 39.90,
    category_id: "cat-doce",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Chocolate"],
    additionals_available: [],
  },
  {
    id: "prod-doc-romeu-julieta",
    name: "Romeu e Julieta",
    photo: "https://images.unsplash.com/photo-1506354666786-959d6d497f1a?w=600&auto=format&fit=crop&q=80",
    description: "O melhor equilíbrio clássico de queijo com goiabada artesanal.",
    ingredients: "Queijo mussarela de base derretido coberto por camadas macias de goiabada cascão cremosa premium.",
    price: 39.90,
    category_id: "cat-doce",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples"],
    additionals_available: [],
  },
  {
    id: "prod-doc-mms",
    name: "M&M's",
    photo: "https://images.unsplash.com/photo-1619535860434-ba1d8fa12536?w=600&auto=format&fit=crop&q=80",
    description: "Chocolate ao leite coberto de confeitos de chocolate coloridos crocantes.",
    ingredients: "Chocolate culinário nobre derretido, salpicado com bastantes pastilhas crocantes tipo M&M's.",
    price: 44.90,
    category_id: "cat-doce",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Chocolate"],
    additionals_available: [],
  },
  {
    id: "prod-doc-ouro-branco",
    name: "Ouro Branco",
    photo: "https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?w=600&auto=format&fit=crop&q=80",
    description: "Sensacional creme de chocolate branco com bombons Ouro Branco picados.",
    ingredients: "Creme de chocolate, base branca refinada e pedaços generosos do bombom Ouro Branco original.",
    price: 44.90,
    category_id: "cat-doce",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Chocolate"],
    additionals_available: [],
  },
  {
    id: "prod-doc-sonho-valsa",
    name: "Sonho de Valsa",
    photo: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&auto=format&fit=crop&q=80",
    description: "Pedaços abundantes de trufas e bombons Sonho de Valsa sobre chocolate.",
    ingredients: "Molho de chocolate ao leite nobre, fatias crocantes dos legítimos bombons Sonho de Valsa originais.",
    price: 44.90,
    category_id: "cat-doce",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Chocolate"],
    additionals_available: [],
  },
  {
    id: "prod-doc-kitkat",
    name: "Kit Kat",
    photo: "https://images.unsplash.com/photo-1619535860434-ba1d8fa12536?w=600&auto=format&fit=crop&q=80",
    description: "Cremoso chocolate sob os tabletes crocantes de wafer Kit Kat.",
    ingredients: "Base de chocolate gourmet premium, coberta por bastões do chocolate Kit Kat wafer original.",
    price: 49.90,
    category_id: "cat-doce",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Chocolate"],
    additionals_available: [],
  },
  {
    id: "prod-doc-bis",
    name: "Bis",
    photo: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&auto=format&fit=crop&q=80",
    description: "A saborosa explosão de chocolate nobre com wafer Bis picadinho.",
    ingredients: "Chocolate ao leite, creme tipo trufa branca e pedacinhos crocantes de Bis chocolate picados.",
    price: 44.90,
    category_id: "cat-doce",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Chocolate"],
    additionals_available: [],
  },
  {
    id: "prod-doc-churros",
    name: "Churros",
    photo: "https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?w=600&auto=format&fit=crop&q=80",
    description: "Maravilhoso recheio de doce de leite argentino salpicado com canela.",
    ingredients: "Doce de leite premium puríssimo espesso, canela salpicada fina com açúcar caramelizado delicioso.",
    price: 44.90,
    category_id: "cat-doce",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples"],
    additionals_available: [],
  },
  {
    id: "prod-doc-pacoca",
    name: "Paçoca",
    photo: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&auto=format&fit=crop&q=80",
    description: "Chocolate cremoso misturado com paçocas de amendoim esfareladas.",
    ingredients: "Ganache de chocolate, doce de leite suave e paçoca de amendoim nobre esfarelada por cima.",
    price: 39.90,
    category_id: "cat-doce",
    active: true,
    is_pizza: true,
    can_half_and_half: true,
    borders_available: ["Massa simples", "Chocolate"],
    additionals_available: [],
  },

  // CATEGORIA: ESFIRRAS SALGADAS (cat-esfirra-salgada)
  {
    id: "prod-esf-sal-carne",
    name: "Carne",
    photo: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80",
    description: "Mini esfirra salgada tradicional individual recheada com carne moída temperada suculenta.",
    ingredients: "Carne bovina moída temperada com limão fresco, cebola, tomates vermelhos e especiarias árabes.",
    price: 4.99,
    category_id: "cat-esfirra-salgada",
    active: true,
    is_pizza: false,
    can_half_and_half: false,
    borders_available: [],
    additionals_available: [],
  },
  {
    id: "prod-esf-sal-queijo",
    name: "Queijo",
    photo: "https://images.unsplash.com/photo-1590947132387-155cc02f3212?w=600&auto=format&fit=crop&q=80",
    description: "Delicioso recheio cremoso com mix de queijos derretidos.",
    ingredients: "Queijo mussarela premium ralado finamente mesclado com queijo minas padrão e tempero verde especial.",
    price: 4.99,
    category_id: "cat-esfirra-salgada",
    active: true,
    is_pizza: false,
    can_half_and_half: false,
    borders_available: [],
    additionals_available: [],
  },
  {
    id: "prod-esf-sal-frango",
    name: "Frango",
    photo: "https://images.unsplash.com/photo-1560684352-8497838a2229?w=600&auto=format&fit=crop&q=80",
    description: "Peito de frango desfiado suculento, levemente refogado com cheiro-verde.",
    ingredients: "Frango caipira cozido e desfiado, temperado com azeite, alho selecionado, cebola picada e salsinha.",
    price: 4.99,
    category_id: "cat-esfirra-salgada",
    active: true,
    is_pizza: false,
    can_half_and_half: false,
    borders_available: [],
    additionals_available: [],
  },
  {
    id: "prod-esf-sal-calabresa",
    name: "Calabresa",
    photo: "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=600&auto=format&fit=crop&q=80",
    description: "Calabresa moída de primeira qualidade com cebola dourada no azeite.",
    ingredients: "Linguiça calabresa defumada moída fina, temperada com cebolas cortadas, orégano e azeite.",
    price: 4.99,
    category_id: "cat-esfirra-salgada",
    active: true,
    is_pizza: false,
    can_half_and_half: false,
    borders_available: [],
    additionals_available: [],
  },
  {
    id: "prod-esf-sal-presunto-queijo",
    name: "Presunto e Queijo",
    photo: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80",
    description: "A clássica misturinha irresistível de presunto cozido picado e queijo derretido.",
    ingredients: "Presunto magro em cubos pequeninos e bastante queijo mussarela elástico.",
    price: 5.99,
    category_id: "cat-esfirra-salgada",
    active: true,
    is_pizza: false,
    can_half_and_half: false,
    borders_available: [],
    additionals_available: [],
  },
  {
    id: "prod-esf-sal-frango-catupiry",
    name: "Frango com Catupiry",
    photo: "https://images.unsplash.com/photo-1544982503-9f984c14501a?w=600&auto=format&fit=crop&q=80",
    description: "Nosso frango desfiado temperado combinado com a cremosidade do requeijão Catupiry.",
    ingredients: "Frango desfiado temperado na panela coberto por generosa camada de requeijão cremoso Catupiry.",
    price: 5.99,
    category_id: "cat-esfirra-salgada",
    active: true,
    is_pizza: false,
    can_half_and_half: false,
    borders_available: [],
    additionals_available: [],
  },
  {
    id: "prod-esf-sal-carne-queijo",
    name: "Carne com Queijo",
    photo: "https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=600&auto=format&fit=crop&q=80",
    description: "A suculenta carne temperada com uma camada de queijo derretido.",
    ingredients: "Carne bovina de primeira moída, temperos árabes tradicionais e cobertura de queijo mussarela.",
    price: 5.99,
    category_id: "cat-esfirra-salgada",
    active: true,
    is_pizza: false,
    can_half_and_half: false,
    borders_available: [],
    additionals_available: [],
  },
  {
    id: "prod-esf-sal-bacon-queijo",
    name: "Bacon com Queijo",
    photo: "https://images.unsplash.com/photo-1613564834361-9436948817d1?w=600&auto=format&fit=crop&q=80",
    description: "Bacon defumado super crocante sob queijo mussarela gratinado.",
    ingredients: "Bacon cortado em cubos dourados e crocantes sobre base generosa de mussarela premium.",
    price: 5.99,
    category_id: "cat-esfirra-salgada",
    active: true,
    is_pizza: false,
    can_half_and_half: false,
    borders_available: [],
    additionals_available: [],
  },
  {
    id: "prod-esf-sal-portuguesa",
    name: "Portuguesa",
    photo: "https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=600&auto=format&fit=crop&q=80",
    description: "Um recheio completo e super saboroso inspirado na pizza portuguesa.",
    ingredients: "Mussarela, presunto picado, rodelas de cebola, ovos cozidos ralados e azeitonas picadas.",
    price: 5.99,
    category_id: "cat-esfirra-salgada",
    active: true,
    is_pizza: false,
    can_half_and_half: false,
    borders_available: [],
    additionals_available: [],
  },
  {
    id: "prod-esf-sal-milho-queijo",
    name: "Milho com Queijo",
    photo: "https://images.unsplash.com/photo-1594007654729-407ededc4963?w=600&auto=format&fit=crop&q=80",
    description: "Milho verde crocante e doce envolto em queijo derretido.",
    ingredients: "Milho selecionado cozido no vapor misturado com queijo mussarela ralado e pitada de sal.",
    price: 5.99,
    category_id: "cat-esfirra-salgada",
    active: true,
    is_pizza: false,
    can_half_and_half: false,
    borders_available: [],
    additionals_available: [],
  },
  {
    id: "prod-esf-sal-brocolis-catupiry",
    name: "Brócolis com Catupiry",
    photo: "https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=600&auto=format&fit=crop&q=80",
    description: "Brócolis frescos cozidos al dente, temperados no alho com Catupiry legítimo.",
    ingredients: "Brócolis frescos picados temperados com azeite e alho frito, com farta cobertura de Catupiry.",
    price: 5.99,
    category_id: "cat-esfirra-salgada",
    active: true,
    is_pizza: false,
    can_half_and_half: false,
    borders_available: [],
    additionals_available: [],
  },
  {
    id: "prod-esf-sal-atum",
    name: "Atum",
    photo: "https://images.unsplash.com/photo-1555072956-7758afb20e8f?w=600&auto=format&fit=crop&q=80",
    description: "Atum ralado refinado temperado com cebola picadinha.",
    ingredients: "Atum sólido de qualidade ao natural desfiado com fios de cebola fresca picada e orégano.",
    price: 5.99,
    category_id: "cat-esfirra-salgada",
    active: true,
    is_pizza: false,
    can_half_and_half: false,
    borders_available: [],
    additionals_available: [],
  },
  {
    id: "prod-esf-sal-palmito",
    name: "Palmito",
    photo: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80",
    description: "Palmito tenro de alta qualidade com um leve tempero especial.",
    ingredients: "Palmito picado em pedaços macios e úmidos condimentado com temperos frescos e azeite.",
    price: 5.99,
    category_id: "cat-esfirra-salgada",
    active: true,
    is_pizza: false,
    can_half_and_half: false,
    borders_available: [],
    additionals_available: [],
  },
  {
    id: "prod-esf-sal-carne-seca-catupiry",
    name: "Carne Seca com Catupiry",
    photo: "https://images.unsplash.com/photo-1590947132387-155cc02f3212?w=600&auto=format&fit=crop&q=80",
    description: "Carne seca desfiada de excelente qualidade com Catupiry legítimo.",
    ingredients: "Carne seca dessalgada, cozida na pressão e desfiada acebolada, enriquecida com Catupiry.",
    price: 6.99,
    category_id: "cat-esfirra-salgada",
    active: true,
    is_pizza: false,
    can_half_and_half: false,
    borders_available: [],
    additionals_available: [],
  },
  {
    id: "prod-esf-sal-quatro-queijos",
    name: "Quatro Queijos",
    photo: "https://images.unsplash.com/photo-1590947132387-155cc02f3212?w=600&auto=format&fit=crop&q=80",
    description: "Mistura incrível com quatro variedades de queijos nobres derretidos.",
    ingredients: "Combinação harmônica de queijo mussarela, queijo provolone aromático, parmesão fino e requeijão Catupiry.",
    price: 6.99,
    category_id: "cat-esfirra-salgada",
    active: true,
    is_pizza: false,
    can_half_and_half: false,
    borders_available: [],
    additionals_available: [],
  },
  {
    id: "prod-esf-sal-pepperoni-queijo",
    name: "Pepperoni com Queijo",
    photo: "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=600&auto=format&fit=crop&q=80",
    description: "Pepperoni condimentado fatiado fino sobre base de mussarela cremosa.",
    ingredients: "Rodelas crocantes de salame tipo pepperoni sob fartura de queijo mussarela premium.",
    price: 6.99,
    category_id: "cat-esfirra-salgada",
    active: true,
    is_pizza: false,
    can_half_and_half: false,
    borders_available: [],
    additionals_available: [],
  },

  // CATEGORIA: ESFIRRAS DOCES (cat-esfirra)
  {
    id: "prod-esf-chocolate",
    name: "Chocolate",
    photo: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&auto=format&fit=crop&q=80",
    description: "Deliciosa mini esfirra doce individual recheada com muito chocolate cremoso.",
    ingredients: "Massa de esfiha super macia, creme de chocolate ao leite premium culinário.",
    price: 4.99,
    category_id: "cat-esfirra",
    active: true,
    is_pizza: false,
    can_half_and_half: false,
    borders_available: [],
    additionals_available: [],
  },
  {
    id: "prod-esf-prestigio",
    name: "Prestígio",
    photo: "https://images.unsplash.com/photo-1619535860434-ba1d8fa12536?w=600&auto=format&fit=crop&q=80",
    description: "Mini esfirra doce com farto creme de chocolate coberta de flocos de coco ralado.",
    ingredients: "Massa selecionada cozida, recheada de chocolate de colher e salpicada de coco úmido.",
    price: 4.99,
    category_id: "cat-esfirra",
    active: true,
    is_pizza: false,
    can_half_and_half: false,
    borders_available: [],
    additionals_available: [],
  },
  {
    id: "prod-esf-brigadeiro",
    name: "Brigadeiro",
    photo: "https://images.unsplash.com/photo-1541783245831-57d6fb0926d3?w=600&auto=format&fit=crop&q=80",
    description: "Individual, recheada de brigadeiro artesanal espesso salpicada com granulado.",
    ingredients: "Brigadeiro gourmet de verdade com chocolate granulado crocante.",
    price: 4.99,
    category_id: "cat-esfirra",
    active: true,
    is_pizza: false,
    can_half_and_half: false,
    borders_available: [],
    additionals_available: [],
  },
  {
    id: "prod-esf-banana",
    name: "Banana com Canela",
    photo: "https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?w=600&auto=format&fit=crop&q=80",
    description: "Massa fresca leve e macia, recheada de fatias de banana assadas com açúcar e canela.",
    ingredients: "Bananas frescas fatiadas finas passadas no açúcar refinado com canela em pó chilena.",
    price: 4.99,
    category_id: "cat-esfirra",
    active: true,
    is_pizza: false,
    can_half_and_half: false,
    borders_available: [],
    additionals_available: [],
  },
  {
    id: "prod-esf-romeu-julieta",
    name: "Romeu e Julieta",
    photo: "https://images.unsplash.com/photo-1506354666786-959d6d497f1a?w=600&auto=format&fit=crop&q=80",
    description: "Massa recheada de queijo derretido saboroso com goiabada cremosa de Minas cascão.",
    ingredients: "Goiabada cremosa cascão, mussarela especial fatiada derretida em mini-esfiha individual.",
    price: 4.99,
    category_id: "cat-esfirra",
    active: true,
    is_pizza: false,
    can_half_and_half: false,
    borders_available: [],
    additionals_available: [],
  },
  {
    id: "prod-esf-cho-branco",
    name: "Chocolate Branco",
    photo: "https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?w=600&auto=format&fit=crop&q=80",
    description: "Recheada de ganache de chocolate branco cremoso premium salpicada.",
    ingredients: "Puro chocolate branco culinário derretido cremoso em massa individual de esfiha doce.",
    price: 5.99,
    category_id: "cat-esfirra",
    active: true,
    is_pizza: false,
    can_half_and_half: false,
    borders_available: [],
    additionals_available: [],
  },
  {
    id: "prod-esf-churros",
    name: "Churros",
    photo: "https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?w=600&auto=format&fit=crop&q=80",
    description: "Estupenda mini-esfirra recheada com autêntico doce de leite e canela.",
    ingredients: "Doce de leite cremoso nobre cozido em fios generosos com pó de canela e açúcar.",
    price: 5.99,
    category_id: "cat-esfirra",
    active: true,
    is_pizza: false,
    can_half_and_half: false,
    borders_available: [],
    additionals_available: [],
  },
  {
    id: "prod-esf-kitkat",
    name: "Kit Kat",
    photo: "https://images.unsplash.com/photo-1619535860434-ba1d8fa12536?w=600&auto=format&fit=crop&q=80",
    description: "Esfirra doce individual com recheio trufado e barras de wrap wafer chocolate Kit Kat.",
    ingredients: "Creme de cacau nobre acompanhado do autêntico chocolate Kit Kat fatiado.",
    price: 6.99,
    category_id: "cat-esfirra",
    active: true,
    is_pizza: false,
    can_half_and_half: false,
    borders_available: [],
    additionals_available: [],
  },
  {
    id: "prod-esf-bis",
    name: "Bis",
    photo: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&auto=format&fit=crop&q=80",
    description: "Doce de chocolate nobre cremoso coroado com confeitos crocantes de Bis picado.",
    ingredients: "Massa doce individual recheada de chocolate, salpicada de wafers de bombons Bis originais.",
    price: 5.99,
    category_id: "cat-esfirra",
    active: true,
    is_pizza: false,
    can_half_and_half: false,
    borders_available: [],
    additionals_available: [],
  },
  {
    id: "prod-esf-pacoca",
    name: "Paçoca",
    photo: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&auto=format&fit=crop&q=80",
    description: "Incrível esfiha com chocolate ganache gourmet coberta de paçoca triturada.",
    ingredients: "Ganache gourmet de chocolate, doce de leite cremoso com amendoins de paçoca moídos.",
    price: 5.99,
    category_id: "cat-esfirra",
    active: true,
    is_pizza: false,
    can_half_and_half: false,
    borders_available: [],
    additionals_available: [],
  },

  // CATEGORIA: BEBIDAS (cat-bebida)
  {
    id: "prod-beb-coca-lata",
    name: "Coca-Cola Lata 350ml",
    photo: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600&auto=format&fit=crop&q=80",
    description: "Lata de Coca-Cola original gelada.",
    ingredients: "Coca-Cola Lata de Alumínio 350ml bem refrigerada.",
    price: 7.00,
    category_id: "cat-bebida",
    active: true,
    is_pizza: false,
    can_half_and_half: false,
    borders_available: [],
    additionals_available: [],
  },
  {
    id: "prod-beb-guarana-lata",
    name: "Guaraná Antarctica Lata 350ml",
    photo: "https://images.unsplash.com/photo-1527960656366-ee5370d9348e?w=600&auto=format&fit=crop&q=80",
    description: "Lata de Guaraná Antarctica bem gelada.",
    ingredients: "Guaraná Antarctica Lata de Alumínio 350ml.",
    price: 7.00,
    category_id: "cat-bebida",
    active: true,
    is_pizza: false,
    can_half_and_half: false,
    borders_available: [],
    additionals_available: [],
  },
  {
    id: "prod-beb-coca-2l",
    name: "Coca-Cola 2 Litros",
    photo: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600&auto=format&fit=crop&q=80",
    description: "Garrafa plástica pet de Coca-Cola de 2 Litros.",
    ingredients: "Refrigerante Coca-Cola 2L em garrafa descartável descartável gelada.",
    price: 15.00,
    category_id: "cat-bebida",
    active: true,
    is_pizza: false,
    can_half_and_half: false,
    borders_available: [],
    additionals_available: [],
  },
  {
    id: "prod-beb-guarana-2l",
    name: "Guaraná Antarctica 2 Litros",
    photo: "https://images.unsplash.com/photo-1527960656366-ee5370d9348e?w=600&auto=format&fit=crop&q=80",
    description: "Garrafa de Guaraná Antarctica trincando de gelada.",
    ingredients: "Guaraná Antarctica Original Pet de 2 Litros.",
    price: 12.00,
    category_id: "cat-bebida",
    active: true,
    is_pizza: false,
    can_half_and_half: false,
    borders_available: [],
    additionals_available: [],
  },
  {
    id: "prod-beb-agua",
    name: "Água Mineral",
    photo: "https://images.unsplash.com/photo-1616118132534-381148898bb4?w=600&auto=format&fit=crop&q=80",
    description: "Garrafa de água mineral pura e altamente refrescante.",
    ingredients: "Água Mineral Natural de Fonte Potável de 500ml.",
    price: 5.00,
    category_id: "cat-bebida",
    active: true,
    is_pizza: false,
    can_half_and_half: false,
    borders_available: [],
    additionals_available: [],
  }
];
